#!/bin/bash

#config s1   (Total:1GB, q0:100Mb, q1:5Mb)
ovs-vsctl -- set Port s1-eth1 qos=@newqos -- set Port s1-eth2 qos=@newqos -- --id=@newqos   create   QoS    type=linux-htb    other-config:max-rate=1000000000 queues=0=@q0,1=@q1 -- --id=@q0   create   Queue   other-config:min-rate=100000000 other-config:max-rate=100000000 -- --id=@q1 create Queue other-config:min-rate=5000000	


#config s2 (Total:1GB, q0:100Mb, q1:5Mb)
ovs-vsctl -- set Port s2-eth1 qos=@newqos -- set Port s2-eth2 qos=@newqos -- --id=@newqos   create   QoS    type=linux-htb    other-config:max-rate=1000000000 queues=0=@q0,1=@q1 -- --id=@q0   create   Queue   other-config:min-rate=100000000 other-config:max-rate=100000000 -- --id=@q1 create Queue other-config:min-rate=5000000	


